platform :ios, '11.0'
use_frameworks!

target 'AppmazoUIKit_Example' do
  pod 'AppmazoUIKit', :path => '../'
# pod 'AppmazoFoundation', :path => '../../AppmazoFoundation'

  target 'AppmazoUIKit_Tests' do
    inherit! :search_paths

    
  end
end
