# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4

language: objective-c

before_install:
 - pod install --project-directory=Example --repo-update
install:
- gem install xcpretty --no-document --quiet
script:
- xcodebuild -workspace Example/AppmazoUIKit.xcworkspace -scheme AppmazoUIKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick
